Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2017
Var
// Seção de Declarações das variáveis 
i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para i<-1 ate 100 faca
     escreval("Olá mundo")
   fimpara

Fimalgoritmo