Algoritmo "exemploPara"
// Disciplina: Fundamentos de programação
// Professor:  Jorge Rabello
// Descrição:  Aqui você descreve o que o programa faz! (função)
// Autor(a):   Nome do(a) aluno(a)
// Data atual: 02/03/2017
Var
   // Seção de Declarações das variáveis
   i : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   // Repete 10 vezes
   para i de 0 ate 10 passo 1 faca
      escreval("REPETINDO ",i)
   fimpara

Fimalgoritmo